version: '3.0'

services:
  front:
    image: oncharterliz/multi-frigate:latest
    environment:
      FRIGATE_PROXY: http://localhost:4000
      OPENID_SERVER: https://server:port/realms/your-realm
      CLIENT_ID: frontend-client
    ports:
      - 80:80 # set your port here