export const strings = {
    host: {
        name: 'Имя хоста',
        url: 'Адрес',
        enabled: 'Включен',
    },
    // user section
    aboutMe: "Обо мне",
    settings: "Настройки",
    changeTheme: "Изменить тему",
    logout: "Выйти",
    userProfile: "Профиль пользователя",
    firstName: "Имя",
    middleName: "Фамилия",
    lastName: "Отчетство",
    taxNumber: "ИНН",
    phone: "Телефон",
    managerName: "Имя менеджера",
    managerPhone: "Телефон менеджера",
    defaultContract: "Договор по умолчанию",
    myShippingAddresses: "Мои адреса доставки:",
    myConditions: "Мои условия:",
    warehouse: "Склад",
    name: "Имя",
    schedule: "Расписание",
    address: "Адрес",
    edit: "Изменить",
    delete: "Удалить",
    error: "Ошибка",
    discounts: "Скидки",
    delivery: "Доставка",
    selectDeliveryMethod: "Выберите метод доставки:",
    pickUpByMyself: "Я заберу самостоятельно",
    courierDelivery: "Доставка курьером",
    deliveryPoint:"Адрес доставки",
    selectYourDeliveryAddress: "Выберите свой адрес доставки:",
    deliveryDate:"Дата доставки",
    selectDeliveryDate: "Выберите дату доставки:",
    enterQuantity: "Введите количество:",
    quantity:"Количество",
    tooltip_close:"нажмите Enter",
    currency:"₽",
    category: "Категории:",
    collapse: "Свернуть",
    hide: "Скрыть",
    show: "Показать",
    showAll: "Показать всё",
    true: "Да",
    false: "Нет",
    // order section
    cart: "Корзина",
    order: "Заказ",
    confirmOrder: "Подтвердить заказ",
    orderParams: "Параметры",
    chooseParams: "Выбрать параметры заказа",
    payment: "Оплата",
    inputPaymentValues: "Ввести платежные данные",
    summary: "Общие итоги",
    positions: "Позиции:",
    weight: "Вес:",
    total: "Итого:",
    confirm: "Подтвердить",
    save: "Сохранить",
    discard: "Отменить",
    next: "Далее",
    back: "Назад",
    paymentMethod: "Метод оплаты",
    selectPaymentMethod: "Выберите метод оплаты",
    cashToCourier: "Наличными курьеру",
    bankTransfer: "Банковским переводом",
    onlineByCard: "Онлайн банковской картой",
    thanksForYourPurchase: "Спасибо за вашу покупку!",
    orderConfirmed: (order: string) => `Ордер ${order} подтвержден!`,
    goToMainPage: "Вернуться на главную",
    goToOrder: "Посмотреть ордер",
    retry: "Повторить",
    youCanRetryOrGoToMain: "Вы можете повторить или вернуться на главную",
    errors: {
        somthengGoesWrong: "Что-то пошло не так",
        cartIsEmpty: "Корзина пуста",
        choosePaymentMethod: "Выберите метод оплаты",
        chooseDeliveryMethod: "Выберите метод доставки",
        chooseDeliveryPoint: "Выберите адрес доставки",
        chooseDate: "Выберите дату",
        403: "Извините у вас нет доступа",
        404: "Извините мы не можем найти такую страницу",

    }
}